# Generated by Django 5.0.3 on 2024-03-12 09:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('textbooks', '0001_initial_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('textbook_page', models.IntegerField(null=True)),
                ('number', models.CharField(db_collation='textbooks_exercise_number')),
                ('instructions', models.TextField(blank=True)),
                ('example', models.TextField(blank=True)),
                ('clue', models.TextField(blank=True)),
                ('wording', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PdfFile',
            fields=[
                ('sha256', models.CharField(max_length=64, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('bytes_count', models.IntegerField()),
                ('pages_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractionEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.TextField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_events', to='textbooks.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='textbooks.project'),
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255, null=True)),
                ('year', models.IntegerField(null=True)),
                ('isbn', models.CharField(max_length=25, null=True, validators=[django.core.validators.RegexValidator('[0-9]')])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbooks', to='textbooks.project')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('textbook_start_page', models.IntegerField()),
                ('pdf_file_start_page', models.IntegerField()),
                ('pages_count', models.IntegerField()),
                ('pdf_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='textbooks.pdffile')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='textbooks.textbook')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='textbook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='textbooks.textbook'),
        ),
        migrations.CreateModel(
            name='PdfFileNaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pdf_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namings', to='textbooks.pdffile')),
            ],
            options={
                'unique_together': {('pdf_file', 'name')},
            },
        ),
        migrations.AddConstraint(
            model_name='textbook',
            constraint=models.UniqueConstraint(models.F('id'), models.F('project'), name='unique_id_and_project_id'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(models.F('textbook'), models.F('textbook_page'), models.F('number'), name='unique_exercise'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('textbook', None), ('textbook_page', None)), models.Q(('textbook__isnull', False), ('textbook_page__isnull', False)), _connector='OR'), name='textbook_and_page_consistently_null'),
        ),
    ]
