# Generated by Django 5.0.4 on 2024-05-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbooks', '0004_adaptedexercise_exercise_bounding_rectangle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectwordsadaptedexercise',
            name='punctuation',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selectwordsadaptedexercise',
            name='words',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name='SelectWordsAdaptedExercise',
            new_name='SelectThingsAdaptedExercise',
        ),
    ]
