# Generated by Django 5.0.4 on 2024-05-15 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbooks', '0005_rename_adaptedexercise_adaptation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoicesAdaptation',
            fields=[
                ('adaptation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='textbooks.adaptation')),
                ('placeholder', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('textbooks.adaptation',),
        ),
    ]
