# Generated by Django 5.0.6 on 2024-05-28 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbooks', '0006_multiplechoicesadaptation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericAdaptation',
            fields=[
                ('adaptation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='textbooks.adaptation')),
                ('generic', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('textbooks.adaptation',),
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ('textbook', 'textbook_page', 'number')},
        ),
    ]
