from alembic import op
import sqlalchemy as sa


revision = "0be827860b2d"
down_revision = "2816939acb1c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("extraction_events_exercise_id_fkey", "extraction_events", type_="foreignkey")
    op.create_foreign_key(None, "extraction_events", "exercises", ["exercise_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("extraction_events_exercise_id_fkey", "extraction_events", type_="foreignkey")
    op.create_foreign_key(
        "extraction_events_exercise_id_fkey", "extraction_events", "exercises", ["exercise_id"], ["id"]
    )
    # ### end Alembic commands ###
