from alembic import op
import sqlalchemy as sa


revision = "6630dab8fc14"
down_revision = "466912d2351b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exercises", sa.Column("wording_paragraphs_per_pagelet", sa.Integer(), server_default="3", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("exercises", "wording_paragraphs_per_pagelet")
    # ### end Alembic commands ###
