from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = "7ef48883e57b"
down_revision = "6630dab8fc14"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("exercises", "bounding_rectangle")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exercises",
        sa.Column("bounding_rectangle", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
