import copy
import json
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm

from gabby.exercises import Exercise


revision = "dd7b7de68daa"
down_revision = "33389ce52383"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

    # Data migration
    with orm.Session(op.get_bind()) as session:
        for exercise in session.query(Exercise).all():
            adaptation = copy.deepcopy(exercise._adaptation)
            if "show_mcq_choices_by_default" not in adaptation["settings"]:
                adaptation["settings"]["show_mcq_choices_by_default"] = False

            exercise._adaptation = adaptation
        session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
