from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm


from gabby.exercises import Exercise


revision = "e27fe2c311ad"
down_revision = "7ef48883e57b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    with orm.Session(op.get_bind()) as session:
        for exercise in session.query(Exercise).all():
            # Fix adaptation
            adaptation = exercise._adaptation
            assert adaptation["format"] == 2
            settings = adaptation["settings"]
            kind = settings["kind"]
            if kind is None or kind == "select-things":
                kind = "generic"
            effects = []
            for effect in settings["effects"]:
                if effect["kind"] == "select-things":
                    assert effect["words"]

                    effect = dict(
                        kind="items-and-effects-attempt-1",
                        items=dict(
                            kind="words",
                            punctuation=effect["punctuation"],
                        ),
                        effects=dict(
                            selectable=dict(
                                colors=effect["colors"],
                            ),
                            boxed=False,
                        ),
                    )
                if effect["kind"] == "items-and-effects-attempt-1":
                    effect["kind"] = "itemized"
                effects.append(effect)
            exercise._adaptation = dict(format=2, settings=dict(kind=kind, effects=effects))

            # Fix instructions, wording, etc.
            exercise._instructions = exercise._instructions + "\n"
            exercise._wording = exercise._wording + "\n"
            exercise._clue = exercise._clue + "\n"
            exercise._example = exercise._example + "\n"

            exercise.instructions = exercise.instructions
            exercise.wording = exercise.wording
            exercise.clue = exercise.clue
            exercise.example = exercise.example
        session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
