/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/batch": {
    /** Batch */
    post: operations["batch_api_batch_post"];
  };
  "/api/exercises": {
    /** Get Exercises */
    get: operations["get_exercises_api_exercises_get"];
    /** Create Exercise */
    post: operations["create_exercise_api_exercises_post"];
  };
  "/api/exercises/{id}": {
    /** Get Exercise */
    get: operations["get_exercise_api_exercises__id__get"];
    /** Delete Exercise */
    delete: operations["delete_exercise_api_exercises__id__delete"];
    /** Update Exercise */
    patch: operations["update_exercise_api_exercises__id__patch"];
  };
  "/api/extractionEvents": {
    /** Get Extraction Events */
    get: operations["get_extraction_events_api_extractionEvents_get"];
    /** Create Extraction Event */
    post: operations["create_extraction_event_api_extractionEvents_post"];
  };
  "/api/extractionEvents/{id}": {
    /** Get Extraction Event */
    get: operations["get_extraction_event_api_extractionEvents__id__get"];
    /** Delete Extraction Event */
    delete: operations["delete_extraction_event_api_extractionEvents__id__delete"];
    /** Update Extraction Event */
    patch: operations["update_extraction_event_api_extractionEvents__id__patch"];
  };
  "/api/fillWithFreeTexts": {
    /** Create Fill With Free Text */
    post: operations["create_fill_with_free_text_api_fillWithFreeTexts_post"];
  };
  "/api/fillWithFreeTexts/{id}": {
    /** Get Fill With Free Text */
    get: operations["get_fill_with_free_text_api_fillWithFreeTexts__id__get"];
    /** Delete Fill With Free Text */
    delete: operations["delete_fill_with_free_text_api_fillWithFreeTexts__id__delete"];
    /** Update Fill With Free Text */
    patch: operations["update_fill_with_free_text_api_fillWithFreeTexts__id__patch"];
  };
  "/api/pdfFileNamings": {
    /** Get Pdf File Namings */
    get: operations["get_pdf_file_namings_api_pdfFileNamings_get"];
    /** Create Pdf File Naming */
    post: operations["create_pdf_file_naming_api_pdfFileNamings_post"];
  };
  "/api/pdfFileNamings/{id}": {
    /** Get Pdf File Naming */
    get: operations["get_pdf_file_naming_api_pdfFileNamings__id__get"];
    /** Delete Pdf File Naming */
    delete: operations["delete_pdf_file_naming_api_pdfFileNamings__id__delete"];
    /** Update Pdf File Naming */
    patch: operations["update_pdf_file_naming_api_pdfFileNamings__id__patch"];
  };
  "/api/pdfFiles": {
    /** Get Pdf Files */
    get: operations["get_pdf_files_api_pdfFiles_get"];
    /** Create Pdf File */
    post: operations["create_pdf_file_api_pdfFiles_post"];
  };
  "/api/pdfFiles/{id}": {
    /** Get Pdf File */
    get: operations["get_pdf_file_api_pdfFiles__id__get"];
    /** Delete Pdf File */
    delete: operations["delete_pdf_file_api_pdfFiles__id__delete"];
    /** Update Pdf File */
    patch: operations["update_pdf_file_api_pdfFiles__id__patch"];
  };
  "/api/pings": {
    /** Get Pings */
    get: operations["get_pings_api_pings_get"];
    /** Create Ping */
    post: operations["create_ping_api_pings_post"];
  };
  "/api/pings/{id}": {
    /** Get Ping */
    get: operations["get_ping_api_pings__id__get"];
    /** Delete Ping */
    delete: operations["delete_ping_api_pings__id__delete"];
    /** Update Ping */
    patch: operations["update_ping_api_pings__id__patch"];
  };
  "/api/project-{project_id}-extraction-report.json": {
    /** Extraction Report */
    get: operations["extraction_report_api_project__project_id__extraction_report_json_get"];
  };
  "/api/project-{project_id}.html": {
    /** Export Project */
    get: operations["export_project_api_project__project_id__html_get"];
  };
  "/api/projects": {
    /** Get Projects */
    get: operations["get_projects_api_projects_get"];
    /** Create Project */
    post: operations["create_project_api_projects_post"];
  };
  "/api/projects/{id}": {
    /** Get Project */
    get: operations["get_project_api_projects__id__get"];
    /** Delete Project */
    delete: operations["delete_project_api_projects__id__delete"];
    /** Update Project */
    patch: operations["update_project_api_projects__id__patch"];
  };
  "/api/sections": {
    /** Get Sections */
    get: operations["get_sections_api_sections_get"];
    /** Create Section */
    post: operations["create_section_api_sections_post"];
  };
  "/api/sections/{id}": {
    /** Get Section */
    get: operations["get_section_api_sections__id__get"];
    /** Delete Section */
    delete: operations["delete_section_api_sections__id__delete"];
    /** Update Section */
    patch: operations["update_section_api_sections__id__patch"];
  };
  "/api/selectWordss": {
    /** Create Select Words */
    post: operations["create_select_words_api_selectWordss_post"];
  };
  "/api/selectWordss/{id}": {
    /** Get Select Words */
    get: operations["get_select_words_api_selectWordss__id__get"];
    /** Delete Select Words */
    delete: operations["delete_select_words_api_selectWordss__id__delete"];
    /** Update Select Words */
    patch: operations["update_select_words_api_selectWordss__id__patch"];
  };
  "/api/textbooks": {
    /** Get Textbooks */
    get: operations["get_textbooks_api_textbooks_get"];
    /** Create Textbook */
    post: operations["create_textbook_api_textbooks_post"];
  };
  "/api/textbooks/{id}": {
    /** Get Textbook */
    get: operations["get_textbook_api_textbooks__id__get"];
    /** Delete Textbook */
    delete: operations["delete_textbook_api_textbooks__id__delete"];
    /** Update Textbook */
    patch: operations["update_textbook_api_textbooks__id__patch"];
  };
  "/api/token": {
    /** Login */
    post: operations["login_api_token_post"];
  };
  "/reset-for-tests/yes-im-sure": {
    /** Reset For Tests */
    post: operations["reset_for_tests_reset_for_tests_yes_im_sure_post"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Body_login_api_token_post */
    Body_login_api_token_post: {
      /** Client Id */
      client_id?: string | null;
      /** Client Secret */
      client_secret?: string | null;
      /** Grant Type */
      grant_type?: string | null;
      /** Options */
      options?: string | null;
      /** Password */
      password: string;
      /**
       * Scope
       * @default
       */
      scope?: string;
      /** Username */
      username: string;
    };
    /** CreateInputListRelationship */
    CreateInputListRelationship: {
      /**
       * Data
       * @default []
       */
      data?: components["schemas"]["ObjectId"][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** ItemLinksModel */
    ItemLinksModel: {
      /** Self */
      self: string;
    };
    /** MandatoryRelationship */
    MandatoryRelationship: {
      data: components["schemas"]["ObjectId"];
    };
    /** Meta */
    Meta: {
      /** Count */
      count: number;
    };
    /** ObjectId */
    ObjectId: {
      /** Id */
      id: string;
      /** Type */
      type: string;
    };
    /** OptionalRelationship */
    OptionalRelationship: {
      data?: components["schemas"]["ObjectId"] | null;
    };
    /** OutputListRelationship */
    OutputListRelationship: {
      /** Data */
      data: components["schemas"]["ObjectId"][];
      meta: components["schemas"]["Meta"];
    };
    /** PageLinksModel */
    PageLinksModel: {
      /** First */
      first: string;
      /** Last */
      last: string;
      /** Next */
      next: string | null;
      /** Prev */
      prev: string | null;
    };
    /** PageMetaModel */
    PageMetaModel: {
      pagination: components["schemas"]["Pagination"];
    };
    /** Pagination */
    Pagination: {
      /** Count */
      count: number;
      /** Page */
      page: number;
      /** Pages */
      pages: number;
    };
    /** Point */
    Point: {
      /** X */
      x: number;
      /** Y */
      y: number;
    };
    /** Rectangle */
    Rectangle: {
      start: components["schemas"]["Point"];
      stop: components["schemas"]["Point"];
    };
    /** UpdateInputListRelationship */
    UpdateInputListRelationship: {
      /** Data */
      data: components["schemas"]["ObjectId"][];
    };
    /** UserModel */
    UserModel: {
      /** Username */
      username: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** exercise-CreateInput */
    "exercise-CreateInput": {
      data: components["schemas"]["exercise-CreateInput-Data"];
    };
    /** exercise-CreateInput-Data */
    "exercise-CreateInput-Data": {
      attributes: components["schemas"]["exercise-CreateInput-Data-Attributes"];
      relationships: components["schemas"]["exercise-CreateInput-Data-Relationships"];
      /** Type */
      type: string;
    };
    /** exercise-CreateInput-Data-Attributes */
    "exercise-CreateInput-Data-Attributes": {
      boundingRectangle?: components["schemas"]["Rectangle"] | null;
      /**
       * Clue
       * @default
       */
      clue?: string;
      /**
       * Example
       * @default
       */
      example?: string;
      /**
       * Instructions
       * @default
       */
      instructions?: string;
      /** Number */
      number: string;
      /** Textbookpage */
      textbookPage?: number | null;
      /**
       * Wording
       * @default
       */
      wording?: string;
    };
    /** exercise-CreateInput-Data-Relationships */
    "exercise-CreateInput-Data-Relationships": {
      /** @default {} */
      adapted?: components["schemas"]["OptionalRelationship"];
      project: components["schemas"]["MandatoryRelationship"];
      /** @default {} */
      textbook?: components["schemas"]["OptionalRelationship"];
    };
    /** exercise-ItemOutput */
    "exercise-ItemOutput": {
      data: components["schemas"]["exercise-OutputItem"];
      /** Included */
      included?: unknown[];
    };
    /** exercise-OutputItem */
    "exercise-OutputItem": {
      attributes: components["schemas"]["exercise-OutputItem-Attributes"];
      /** Id */
      id: string;
      links: components["schemas"]["ItemLinksModel"];
      relationships: components["schemas"]["exercise-OutputItem-Relationships"];
      /** Type */
      type: string;
    };
    /** exercise-OutputItem-Attributes */
    "exercise-OutputItem-Attributes": {
      boundingRectangle: components["schemas"]["Rectangle"] | null;
      /** Clue */
      clue: string;
      /** Example */
      example: string;
      /** Instructions */
      instructions: string;
      /** Number */
      number: string;
      /** Textbookpage */
      textbookPage: number | null;
      /** Wording */
      wording: string;
    };
    /** exercise-OutputItem-Relationships */
    "exercise-OutputItem-Relationships": {
      adapted: components["schemas"]["OptionalRelationship"];
      extractionEvents: components["schemas"]["OutputListRelationship"];
      project: components["schemas"]["MandatoryRelationship"];
      textbook: components["schemas"]["OptionalRelationship"];
    };
    /** exercise-PageOutput */
    "exercise-PageOutput": {
      /** Data */
      data: components["schemas"]["exercise-OutputItem"][];
      /** Included */
      included?: unknown[];
      links: components["schemas"]["PageLinksModel"];
      meta: components["schemas"]["PageMetaModel"];
    };
    /** exercise-UpdateInput */
    "exercise-UpdateInput": {
      data: components["schemas"]["exercise-UpdateInput-Data"];
    };
    /** exercise-UpdateInput-Data */
    "exercise-UpdateInput-Data": {
      /** @default {} */
      attributes?: components["schemas"]["exercise-UpdateInput-Data-Attributes"];
      /** Id */
      id: string;
      /** @default {} */
      relationships?: components["schemas"]["exercise-UpdateInput-Data-Relationships"];
      /** Type */
      type: string;
    };
    /** exercise-UpdateInput-Data-Attributes */
    "exercise-UpdateInput-Data-Attributes": {
      boundingRectangle?: components["schemas"]["Rectangle"] | null;
      /** Clue */
      clue?: string;
      /** Example */
      example?: string;
      /** Instructions */
      instructions?: string;
      /** Wording */
      wording?: string;
    };
    /** exercise-UpdateInput-Data-Relationships */
    "exercise-UpdateInput-Data-Relationships": {
      adapted?: components["schemas"]["OptionalRelationship"];
    };
    /** extractionEvent-CreateInput */
    "extractionEvent-CreateInput": {
      data: components["schemas"]["extractionEvent-CreateInput-Data"];
    };
    /** extractionEvent-CreateInput-Data */
    "extractionEvent-CreateInput-Data": {
      attributes: components["schemas"]["extractionEvent-CreateInput-Data-Attributes"];
      relationships: components["schemas"]["extractionEvent-CreateInput-Data-Relationships"];
      /** Type */
      type: string;
    };
    /** extractionEvent-CreateInput-Data-Attributes */
    "extractionEvent-CreateInput-Data-Attributes": {
      /** Event */
      event: string;
    };
    /** extractionEvent-CreateInput-Data-Relationships */
    "extractionEvent-CreateInput-Data-Relationships": {
      exercise: components["schemas"]["MandatoryRelationship"];
    };
    /** extractionEvent-ItemOutput */
    "extractionEvent-ItemOutput": {
      data: components["schemas"]["extractionEvent-OutputItem"];
      /** Included */
      included?: unknown[];
    };
    /** extractionEvent-OutputItem */
    "extractionEvent-OutputItem": {
      attributes: components["schemas"]["extractionEvent-OutputItem-Attributes"];
      /** Id */
      id: string;
      links: components["schemas"]["ItemLinksModel"];
      relationships: components["schemas"]["extractionEvent-OutputItem-Relationships"];
      /** Type */
      type: string;
    };
    /** extractionEvent-OutputItem-Attributes */
    "extractionEvent-OutputItem-Attributes": {
      /** Event */
      event: string;
    };
    /** extractionEvent-OutputItem-Relationships */
    "extractionEvent-OutputItem-Relationships": {
      exercise: components["schemas"]["MandatoryRelationship"];
    };
    /** extractionEvent-PageOutput */
    "extractionEvent-PageOutput": {
      /** Data */
      data: components["schemas"]["extractionEvent-OutputItem"][];
      /** Included */
      included?: unknown[];
      links: components["schemas"]["PageLinksModel"];
      meta: components["schemas"]["PageMetaModel"];
    };
    /** extractionEvent-UpdateInput */
    "extractionEvent-UpdateInput": {
      data: components["schemas"]["extractionEvent-UpdateInput-Data"];
    };
    /** extractionEvent-UpdateInput-Data */
    "extractionEvent-UpdateInput-Data": {
      /** @default {} */
      attributes?: components["schemas"]["extractionEvent-UpdateInput-Data-Attributes"];
      /** Id */
      id: string;
      /** @default {} */
      relationships?: components["schemas"]["extractionEvent-UpdateInput-Data-Relationships"];
      /** Type */
      type: string;
    };
    /** extractionEvent-UpdateInput-Data-Attributes */
    "extractionEvent-UpdateInput-Data-Attributes": Record<string, never>;
    /** extractionEvent-UpdateInput-Data-Relationships */
    "extractionEvent-UpdateInput-Data-Relationships": Record<string, never>;
    /** fillWithFreeText-CreateInput */
    "fillWithFreeText-CreateInput": {
      data: components["schemas"]["fillWithFreeText-CreateInput-Data"];
    };
    /** fillWithFreeText-CreateInput-Data */
    "fillWithFreeText-CreateInput-Data": {
      attributes: components["schemas"]["fillWithFreeText-CreateInput-Data-Attributes"];
      relationships: components["schemas"]["fillWithFreeText-CreateInput-Data-Relationships"];
      /** Type */
      type: string;
    };
    /** fillWithFreeText-CreateInput-Data-Attributes */
    "fillWithFreeText-CreateInput-Data-Attributes": {
      /** Placeholder */
      placeholder: string;
    };
    /** fillWithFreeText-CreateInput-Data-Relationships */
    "fillWithFreeText-CreateInput-Data-Relationships": {
      exercise: components["schemas"]["MandatoryRelationship"];
    };
    /** fillWithFreeText-ItemOutput */
    "fillWithFreeText-ItemOutput": {
      data: components["schemas"]["fillWithFreeText-OutputItem"];
      /** Included */
      included?: unknown[];
    };
    /** fillWithFreeText-OutputItem */
    "fillWithFreeText-OutputItem": {
      attributes: components["schemas"]["fillWithFreeText-OutputItem-Attributes"];
      /** Id */
      id: string;
      links: components["schemas"]["ItemLinksModel"];
      relationships: components["schemas"]["fillWithFreeText-OutputItem-Relationships"];
      /** Type */
      type: string;
    };
    /** fillWithFreeText-OutputItem-Attributes */
    "fillWithFreeText-OutputItem-Attributes": {
      /** Placeholder */
      placeholder: string;
    };
    /** fillWithFreeText-OutputItem-Relationships */
    "fillWithFreeText-OutputItem-Relationships": {
      exercise: components["schemas"]["MandatoryRelationship"];
    };
    /** fillWithFreeText-UpdateInput */
    "fillWithFreeText-UpdateInput": {
      data: components["schemas"]["fillWithFreeText-UpdateInput-Data"];
    };
    /** fillWithFreeText-UpdateInput-Data */
    "fillWithFreeText-UpdateInput-Data": {
      /** @default {} */
      attributes?: components["schemas"]["fillWithFreeText-UpdateInput-Data-Attributes"];
      /** Id */
      id: string;
      /** @default {} */
      relationships?: components["schemas"]["fillWithFreeText-UpdateInput-Data-Relationships"];
      /** Type */
      type: string;
    };
    /** fillWithFreeText-UpdateInput-Data-Attributes */
    "fillWithFreeText-UpdateInput-Data-Attributes": {
      /** Placeholder */
      placeholder?: string;
    };
    /** fillWithFreeText-UpdateInput-Data-Relationships */
    "fillWithFreeText-UpdateInput-Data-Relationships": Record<string, never>;
    /** pdfFile-CreateInput */
    "pdfFile-CreateInput": {
      data: components["schemas"]["pdfFile-CreateInput-Data"];
    };
    /** pdfFile-CreateInput-Data */
    "pdfFile-CreateInput-Data": {
      attributes: components["schemas"]["pdfFile-CreateInput-Data-Attributes"];
      /** @default {} */
      relationships?: components["schemas"]["pdfFile-CreateInput-Data-Relationships"];
      /** Type */
      type: string;
    };
    /** pdfFile-CreateInput-Data-Attributes */
    "pdfFile-CreateInput-Data-Attributes": {
      /** Bytescount */
      bytesCount: number;
      /** Pagescount */
      pagesCount: number;
      /** Sha256 */
      sha256: string;
    };
    /** pdfFile-CreateInput-Data-Relationships */
    "pdfFile-CreateInput-Data-Relationships": Record<string, never>;
    /** pdfFile-ItemOutput */
    "pdfFile-ItemOutput": {
      data: components["schemas"]["pdfFile-OutputItem"];
      /** Included */
      included?: unknown[];
    };
    /** pdfFile-OutputItem */
    "pdfFile-OutputItem": {
      attributes: components["schemas"]["pdfFile-OutputItem-Attributes"];
      /** Id */
      id: string;
      links: components["schemas"]["ItemLinksModel"];
      relationships: components["schemas"]["pdfFile-OutputItem-Relationships"];
      /** Type */
      type: string;
    };
    /** pdfFile-OutputItem-Attributes */
    "pdfFile-OutputItem-Attributes": {
      /** Bytescount */
      bytesCount: number;
      /** Pagescount */
      pagesCount: number;
      /** Sha256 */
      sha256: string;
    };
    /** pdfFile-OutputItem-Relationships */
    "pdfFile-OutputItem-Relationships": {
      namings: components["schemas"]["OutputListRelationship"];
      sections: components["schemas"]["OutputListRelationship"];
    };
    /** pdfFile-PageOutput */
    "pdfFile-PageOutput": {
      /** Data */
      data: components["schemas"]["pdfFile-OutputItem"][];
      /** Included */
      included?: unknown[];
      links: components["schemas"]["PageLinksModel"];
      meta: components["schemas"]["PageMetaModel"];
    };
    /** pdfFile-UpdateInput */
    "pdfFile-UpdateInput": {
      data: components["schemas"]["pdfFile-UpdateInput-Data"];
    };
    /** pdfFile-UpdateInput-Data */
    "pdfFile-UpdateInput-Data": {
      /** @default {} */
      attributes?: components["schemas"]["pdfFile-UpdateInput-Data-Attributes"];
      /** Id */
      id: string;
      /** @default {} */
      relationships?: components["schemas"]["pdfFile-UpdateInput-Data-Relationships"];
      /** Type */
      type: string;
    };
    /** pdfFile-UpdateInput-Data-Attributes */
    "pdfFile-UpdateInput-Data-Attributes": Record<string, never>;
    /** pdfFile-UpdateInput-Data-Relationships */
    "pdfFile-UpdateInput-Data-Relationships": Record<string, never>;
    /** pdfFileNaming-CreateInput */
    "pdfFileNaming-CreateInput": {
      data: components["schemas"]["pdfFileNaming-CreateInput-Data"];
    };
    /** pdfFileNaming-CreateInput-Data */
    "pdfFileNaming-CreateInput-Data": {
      attributes: components["schemas"]["pdfFileNaming-CreateInput-Data-Attributes"];
      relationships: components["schemas"]["pdfFileNaming-CreateInput-Data-Relationships"];
      /** Type */
      type: string;
    };
    /** pdfFileNaming-CreateInput-Data-Attributes */
    "pdfFileNaming-CreateInput-Data-Attributes": {
      /** Name */
      name: string;
    };
    /** pdfFileNaming-CreateInput-Data-Relationships */
    "pdfFileNaming-CreateInput-Data-Relationships": {
      pdfFile: components["schemas"]["MandatoryRelationship"];
    };
    /** pdfFileNaming-ItemOutput */
    "pdfFileNaming-ItemOutput": {
      data: components["schemas"]["pdfFileNaming-OutputItem"];
      /** Included */
      included?: unknown[];
    };
    /** pdfFileNaming-OutputItem */
    "pdfFileNaming-OutputItem": {
      attributes: components["schemas"]["pdfFileNaming-OutputItem-Attributes"];
      /** Id */
      id: string;
      links: components["schemas"]["ItemLinksModel"];
      relationships: components["schemas"]["pdfFileNaming-OutputItem-Relationships"];
      /** Type */
      type: string;
    };
    /** pdfFileNaming-OutputItem-Attributes */
    "pdfFileNaming-OutputItem-Attributes": {
      /** Name */
      name: string;
    };
    /** pdfFileNaming-OutputItem-Relationships */
    "pdfFileNaming-OutputItem-Relationships": {
      pdfFile: components["schemas"]["MandatoryRelationship"];
    };
    /** pdfFileNaming-PageOutput */
    "pdfFileNaming-PageOutput": {
      /** Data */
      data: components["schemas"]["pdfFileNaming-OutputItem"][];
      /** Included */
      included?: unknown[];
      links: components["schemas"]["PageLinksModel"];
      meta: components["schemas"]["PageMetaModel"];
    };
    /** pdfFileNaming-UpdateInput */
    "pdfFileNaming-UpdateInput": {
      data: components["schemas"]["pdfFileNaming-UpdateInput-Data"];
    };
    /** pdfFileNaming-UpdateInput-Data */
    "pdfFileNaming-UpdateInput-Data": {
      /** @default {} */
      attributes?: components["schemas"]["pdfFileNaming-UpdateInput-Data-Attributes"];
      /** Id */
      id: string;
      /** @default {} */
      relationships?: components["schemas"]["pdfFileNaming-UpdateInput-Data-Relationships"];
      /** Type */
      type: string;
    };
    /** pdfFileNaming-UpdateInput-Data-Attributes */
    "pdfFileNaming-UpdateInput-Data-Attributes": Record<string, never>;
    /** pdfFileNaming-UpdateInput-Data-Relationships */
    "pdfFileNaming-UpdateInput-Data-Relationships": Record<string, never>;
    /** ping-CreateInput */
    "ping-CreateInput": {
      data: components["schemas"]["ping-CreateInput-Data"];
    };
    /** ping-CreateInput-Data */
    "ping-CreateInput-Data": {
      /** @default {} */
      attributes?: components["schemas"]["ping-CreateInput-Data-Attributes"];
      /**
       * @default {
       *   "next": {
       *     "data": []
       *   },
       *   "prev": {}
       * }
       */
      relationships?: components["schemas"]["ping-CreateInput-Data-Relationships"];
      /** Type */
      type: string;
    };
    /** ping-CreateInput-Data-Attributes */
    "ping-CreateInput-Data-Attributes": {
      /** Message */
      message?: string | null;
    };
    /** ping-CreateInput-Data-Relationships */
    "ping-CreateInput-Data-Relationships": {
      /**
       * @default {
       *   "data": []
       * }
       */
      next?: components["schemas"]["CreateInputListRelationship"];
      /** @default {} */
      prev?: components["schemas"]["OptionalRelationship"];
    };
    /** ping-ItemOutput */
    "ping-ItemOutput": {
      data: components["schemas"]["ping-OutputItem"];
      /** Included */
      included?: unknown[];
    };
    /** ping-OutputItem */
    "ping-OutputItem": {
      attributes: components["schemas"]["ping-OutputItem-Attributes"];
      /** Id */
      id: string;
      links: components["schemas"]["ItemLinksModel"];
      relationships: components["schemas"]["ping-OutputItem-Relationships"];
      /** Type */
      type: string;
    };
    /** ping-OutputItem-Attributes */
    "ping-OutputItem-Attributes": {
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
      createdBy: components["schemas"]["UserModel"] | null;
      /** Message */
      message: string | null;
      /**
       * Updatedat
       * Format: date-time
       */
      updatedAt: string;
      updatedBy: components["schemas"]["UserModel"] | null;
    };
    /** ping-OutputItem-Relationships */
    "ping-OutputItem-Relationships": {
      next: components["schemas"]["OutputListRelationship"];
      prev: components["schemas"]["OptionalRelationship"];
    };
    /** ping-PageOutput */
    "ping-PageOutput": {
      /** Data */
      data: components["schemas"]["ping-OutputItem"][];
      /** Included */
      included?: unknown[];
      links: components["schemas"]["PageLinksModel"];
      meta: components["schemas"]["PageMetaModel"];
    };
    /** ping-UpdateInput */
    "ping-UpdateInput": {
      data: components["schemas"]["ping-UpdateInput-Data"];
    };
    /** ping-UpdateInput-Data */
    "ping-UpdateInput-Data": {
      /** @default {} */
      attributes?: components["schemas"]["ping-UpdateInput-Data-Attributes"];
      /** Id */
      id: string;
      /** @default {} */
      relationships?: components["schemas"]["ping-UpdateInput-Data-Relationships"];
      /** Type */
      type: string;
    };
    /** ping-UpdateInput-Data-Attributes */
    "ping-UpdateInput-Data-Attributes": {
      /** Message */
      message?: string | null;
    };
    /** ping-UpdateInput-Data-Relationships */
    "ping-UpdateInput-Data-Relationships": {
      next?: components["schemas"]["UpdateInputListRelationship"];
      prev?: components["schemas"]["OptionalRelationship"];
    };
    /** project-CreateInput */
    "project-CreateInput": {
      data: components["schemas"]["project-CreateInput-Data"];
    };
    /** project-CreateInput-Data */
    "project-CreateInput-Data": {
      attributes: components["schemas"]["project-CreateInput-Data-Attributes"];
      /** @default {} */
      relationships?: components["schemas"]["project-CreateInput-Data-Relationships"];
      /** Type */
      type: string;
    };
    /** project-CreateInput-Data-Attributes */
    "project-CreateInput-Data-Attributes": {
      /**
       * Description
       * @default
       */
      description?: string;
      /** Title */
      title: string;
    };
    /** project-CreateInput-Data-Relationships */
    "project-CreateInput-Data-Relationships": Record<string, never>;
    /** project-ItemOutput */
    "project-ItemOutput": {
      data: components["schemas"]["project-OutputItem"];
      /** Included */
      included?: unknown[];
    };
    /** project-OutputItem */
    "project-OutputItem": {
      attributes: components["schemas"]["project-OutputItem-Attributes"];
      /** Id */
      id: string;
      links: components["schemas"]["ItemLinksModel"];
      relationships: components["schemas"]["project-OutputItem-Relationships"];
      /** Type */
      type: string;
    };
    /** project-OutputItem-Attributes */
    "project-OutputItem-Attributes": {
      /** Description */
      description: string;
      /** Title */
      title: string;
    };
    /** project-OutputItem-Relationships */
    "project-OutputItem-Relationships": {
      exercises: components["schemas"]["OutputListRelationship"];
      textbooks: components["schemas"]["OutputListRelationship"];
    };
    /** project-PageOutput */
    "project-PageOutput": {
      /** Data */
      data: components["schemas"]["project-OutputItem"][];
      /** Included */
      included?: unknown[];
      links: components["schemas"]["PageLinksModel"];
      meta: components["schemas"]["PageMetaModel"];
    };
    /** project-UpdateInput */
    "project-UpdateInput": {
      data: components["schemas"]["project-UpdateInput-Data"];
    };
    /** project-UpdateInput-Data */
    "project-UpdateInput-Data": {
      /** @default {} */
      attributes?: components["schemas"]["project-UpdateInput-Data-Attributes"];
      /** Id */
      id: string;
      /** @default {} */
      relationships?: components["schemas"]["project-UpdateInput-Data-Relationships"];
      /** Type */
      type: string;
    };
    /** project-UpdateInput-Data-Attributes */
    "project-UpdateInput-Data-Attributes": {
      /** Description */
      description?: string;
      /** Title */
      title?: string;
    };
    /** project-UpdateInput-Data-Relationships */
    "project-UpdateInput-Data-Relationships": Record<string, never>;
    /** section-CreateInput */
    "section-CreateInput": {
      data: components["schemas"]["section-CreateInput-Data"];
    };
    /** section-CreateInput-Data */
    "section-CreateInput-Data": {
      attributes: components["schemas"]["section-CreateInput-Data-Attributes"];
      relationships: components["schemas"]["section-CreateInput-Data-Relationships"];
      /** Type */
      type: string;
    };
    /** section-CreateInput-Data-Attributes */
    "section-CreateInput-Data-Attributes": {
      /** Pagescount */
      pagesCount: number;
      /** Pdffilestartpage */
      pdfFileStartPage: number;
      /** Textbookstartpage */
      textbookStartPage: number;
    };
    /** section-CreateInput-Data-Relationships */
    "section-CreateInput-Data-Relationships": {
      pdfFile: components["schemas"]["MandatoryRelationship"];
      textbook: components["schemas"]["MandatoryRelationship"];
    };
    /** section-ItemOutput */
    "section-ItemOutput": {
      data: components["schemas"]["section-OutputItem"];
      /** Included */
      included?: unknown[];
    };
    /** section-OutputItem */
    "section-OutputItem": {
      attributes: components["schemas"]["section-OutputItem-Attributes"];
      /** Id */
      id: string;
      links: components["schemas"]["ItemLinksModel"];
      relationships: components["schemas"]["section-OutputItem-Relationships"];
      /** Type */
      type: string;
    };
    /** section-OutputItem-Attributes */
    "section-OutputItem-Attributes": {
      /** Pagescount */
      pagesCount: number;
      /** Pdffilestartpage */
      pdfFileStartPage: number;
      /** Textbookstartpage */
      textbookStartPage: number;
    };
    /** section-OutputItem-Relationships */
    "section-OutputItem-Relationships": {
      pdfFile: components["schemas"]["MandatoryRelationship"];
      textbook: components["schemas"]["MandatoryRelationship"];
    };
    /** section-PageOutput */
    "section-PageOutput": {
      /** Data */
      data: components["schemas"]["section-OutputItem"][];
      /** Included */
      included?: unknown[];
      links: components["schemas"]["PageLinksModel"];
      meta: components["schemas"]["PageMetaModel"];
    };
    /** section-UpdateInput */
    "section-UpdateInput": {
      data: components["schemas"]["section-UpdateInput-Data"];
    };
    /** section-UpdateInput-Data */
    "section-UpdateInput-Data": {
      /** @default {} */
      attributes?: components["schemas"]["section-UpdateInput-Data-Attributes"];
      /** Id */
      id: string;
      /** @default {} */
      relationships?: components["schemas"]["section-UpdateInput-Data-Relationships"];
      /** Type */
      type: string;
    };
    /** section-UpdateInput-Data-Attributes */
    "section-UpdateInput-Data-Attributes": {
      /** Pagescount */
      pagesCount?: number;
      /** Pdffilestartpage */
      pdfFileStartPage?: number;
      /** Textbookstartpage */
      textbookStartPage?: number;
    };
    /** section-UpdateInput-Data-Relationships */
    "section-UpdateInput-Data-Relationships": Record<string, never>;
    /** selectWords-CreateInput */
    "selectWords-CreateInput": {
      data: components["schemas"]["selectWords-CreateInput-Data"];
    };
    /** selectWords-CreateInput-Data */
    "selectWords-CreateInput-Data": {
      attributes: components["schemas"]["selectWords-CreateInput-Data-Attributes"];
      relationships: components["schemas"]["selectWords-CreateInput-Data-Relationships"];
      /** Type */
      type: string;
    };
    /** selectWords-CreateInput-Data-Attributes */
    "selectWords-CreateInput-Data-Attributes": {
      /** Colors */
      colors: number;
    };
    /** selectWords-CreateInput-Data-Relationships */
    "selectWords-CreateInput-Data-Relationships": {
      exercise: components["schemas"]["MandatoryRelationship"];
    };
    /** selectWords-ItemOutput */
    "selectWords-ItemOutput": {
      data: components["schemas"]["selectWords-OutputItem"];
      /** Included */
      included?: unknown[];
    };
    /** selectWords-OutputItem */
    "selectWords-OutputItem": {
      attributes: components["schemas"]["selectWords-OutputItem-Attributes"];
      /** Id */
      id: string;
      links: components["schemas"]["ItemLinksModel"];
      relationships: components["schemas"]["selectWords-OutputItem-Relationships"];
      /** Type */
      type: string;
    };
    /** selectWords-OutputItem-Attributes */
    "selectWords-OutputItem-Attributes": {
      /** Colors */
      colors: number;
    };
    /** selectWords-OutputItem-Relationships */
    "selectWords-OutputItem-Relationships": {
      exercise: components["schemas"]["MandatoryRelationship"];
    };
    /** selectWords-UpdateInput */
    "selectWords-UpdateInput": {
      data: components["schemas"]["selectWords-UpdateInput-Data"];
    };
    /** selectWords-UpdateInput-Data */
    "selectWords-UpdateInput-Data": {
      /** @default {} */
      attributes?: components["schemas"]["selectWords-UpdateInput-Data-Attributes"];
      /** Id */
      id: string;
      /** @default {} */
      relationships?: components["schemas"]["selectWords-UpdateInput-Data-Relationships"];
      /** Type */
      type: string;
    };
    /** selectWords-UpdateInput-Data-Attributes */
    "selectWords-UpdateInput-Data-Attributes": {
      /** Colors */
      colors?: number;
    };
    /** selectWords-UpdateInput-Data-Relationships */
    "selectWords-UpdateInput-Data-Relationships": Record<string, never>;
    /** textbook-CreateInput */
    "textbook-CreateInput": {
      data: components["schemas"]["textbook-CreateInput-Data"];
    };
    /** textbook-CreateInput-Data */
    "textbook-CreateInput-Data": {
      attributes: components["schemas"]["textbook-CreateInput-Data-Attributes"];
      relationships: components["schemas"]["textbook-CreateInput-Data-Relationships"];
      /** Type */
      type: string;
    };
    /** textbook-CreateInput-Data-Attributes */
    "textbook-CreateInput-Data-Attributes": {
      /** Isbn */
      isbn?: string | null;
      /** Publisher */
      publisher?: string | null;
      /** Title */
      title: string;
      /** Year */
      year?: number | null;
    };
    /** textbook-CreateInput-Data-Relationships */
    "textbook-CreateInput-Data-Relationships": {
      project: components["schemas"]["MandatoryRelationship"];
    };
    /** textbook-ItemOutput */
    "textbook-ItemOutput": {
      data: components["schemas"]["textbook-OutputItem"];
      /** Included */
      included?: unknown[];
    };
    /** textbook-OutputItem */
    "textbook-OutputItem": {
      attributes: components["schemas"]["textbook-OutputItem-Attributes"];
      /** Id */
      id: string;
      links: components["schemas"]["ItemLinksModel"];
      relationships: components["schemas"]["textbook-OutputItem-Relationships"];
      /** Type */
      type: string;
    };
    /** textbook-OutputItem-Attributes */
    "textbook-OutputItem-Attributes": {
      /** Isbn */
      isbn: string | null;
      /** Publisher */
      publisher: string | null;
      /** Title */
      title: string;
      /** Year */
      year: number | null;
    };
    /** textbook-OutputItem-Relationships */
    "textbook-OutputItem-Relationships": {
      exercises: components["schemas"]["OutputListRelationship"];
      project: components["schemas"]["MandatoryRelationship"];
      sections: components["schemas"]["OutputListRelationship"];
    };
    /** textbook-PageOutput */
    "textbook-PageOutput": {
      /** Data */
      data: components["schemas"]["textbook-OutputItem"][];
      /** Included */
      included?: unknown[];
      links: components["schemas"]["PageLinksModel"];
      meta: components["schemas"]["PageMetaModel"];
    };
    /** textbook-UpdateInput */
    "textbook-UpdateInput": {
      data: components["schemas"]["textbook-UpdateInput-Data"];
    };
    /** textbook-UpdateInput-Data */
    "textbook-UpdateInput-Data": {
      /** @default {} */
      attributes?: components["schemas"]["textbook-UpdateInput-Data-Attributes"];
      /** Id */
      id: string;
      /** @default {} */
      relationships?: components["schemas"]["textbook-UpdateInput-Data-Relationships"];
      /** Type */
      type: string;
    };
    /** textbook-UpdateInput-Data-Attributes */
    "textbook-UpdateInput-Data-Attributes": {
      /** Isbn */
      isbn?: string | null;
      /** Publisher */
      publisher?: string | null;
      /** Title */
      title?: string;
      /** Year */
      year?: number | null;
    };
    /** textbook-UpdateInput-Data-Relationships */
    "textbook-UpdateInput-Data-Relationships": Record<string, never>;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Batch */
  batch_api_batch_post: {
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Exercises */
  get_exercises_api_exercises_get: {
    parameters: {
      query?: {
        "page[size]"?: number;
        "page[number]"?: number;
        sort?: string;
        include?: string;
        "filter[textbook]"?: string;
        "filter[textbookPage]"?: number;
        "filter[number]"?: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["exercise-PageOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Exercise */
  create_exercise_api_exercises_post: {
    parameters: {
      query?: {
        include?: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["exercise-CreateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/vnd.api+json": components["schemas"]["exercise-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Exercise */
  get_exercise_api_exercises__id__get: {
    parameters: {
      query?: {
        include?: string;
      };
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["exercise-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Exercise */
  delete_exercise_api_exercises__id__delete: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Exercise */
  update_exercise_api_exercises__id__patch: {
    parameters: {
      query?: {
        include?: string;
      };
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["exercise-UpdateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["exercise-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Extraction Events */
  get_extraction_events_api_extractionEvents_get: {
    parameters: {
      query?: {
        "page[size]"?: number;
        "page[number]"?: number;
        sort?: string;
        include?: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["extractionEvent-PageOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Extraction Event */
  create_extraction_event_api_extractionEvents_post: {
    parameters: {
      query?: {
        include?: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["extractionEvent-CreateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/vnd.api+json": components["schemas"]["extractionEvent-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Extraction Event */
  get_extraction_event_api_extractionEvents__id__get: {
    parameters: {
      query?: {
        include?: string;
      };
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["extractionEvent-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Extraction Event */
  delete_extraction_event_api_extractionEvents__id__delete: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Extraction Event */
  update_extraction_event_api_extractionEvents__id__patch: {
    parameters: {
      query?: {
        include?: string;
      };
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["extractionEvent-UpdateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["extractionEvent-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Fill With Free Text */
  create_fill_with_free_text_api_fillWithFreeTexts_post: {
    parameters: {
      query?: {
        include?: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["fillWithFreeText-CreateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/vnd.api+json": components["schemas"]["fillWithFreeText-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Fill With Free Text */
  get_fill_with_free_text_api_fillWithFreeTexts__id__get: {
    parameters: {
      query?: {
        include?: string;
      };
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["fillWithFreeText-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Fill With Free Text */
  delete_fill_with_free_text_api_fillWithFreeTexts__id__delete: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Fill With Free Text */
  update_fill_with_free_text_api_fillWithFreeTexts__id__patch: {
    parameters: {
      query?: {
        include?: string;
      };
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["fillWithFreeText-UpdateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["fillWithFreeText-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Pdf File Namings */
  get_pdf_file_namings_api_pdfFileNamings_get: {
    parameters: {
      query?: {
        "page[size]"?: number;
        "page[number]"?: number;
        sort?: string;
        include?: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["pdfFileNaming-PageOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Pdf File Naming */
  create_pdf_file_naming_api_pdfFileNamings_post: {
    parameters: {
      query?: {
        include?: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["pdfFileNaming-CreateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/vnd.api+json": components["schemas"]["pdfFileNaming-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Pdf File Naming */
  get_pdf_file_naming_api_pdfFileNamings__id__get: {
    parameters: {
      query?: {
        include?: string;
      };
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["pdfFileNaming-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Pdf File Naming */
  delete_pdf_file_naming_api_pdfFileNamings__id__delete: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Pdf File Naming */
  update_pdf_file_naming_api_pdfFileNamings__id__patch: {
    parameters: {
      query?: {
        include?: string;
      };
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["pdfFileNaming-UpdateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["pdfFileNaming-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Pdf Files */
  get_pdf_files_api_pdfFiles_get: {
    parameters: {
      query?: {
        "page[size]"?: number;
        "page[number]"?: number;
        sort?: string;
        include?: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["pdfFile-PageOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Pdf File */
  create_pdf_file_api_pdfFiles_post: {
    parameters: {
      query?: {
        include?: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["pdfFile-CreateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/vnd.api+json": components["schemas"]["pdfFile-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Pdf File */
  get_pdf_file_api_pdfFiles__id__get: {
    parameters: {
      query?: {
        include?: string;
      };
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["pdfFile-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Pdf File */
  delete_pdf_file_api_pdfFiles__id__delete: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Pdf File */
  update_pdf_file_api_pdfFiles__id__patch: {
    parameters: {
      query?: {
        include?: string;
      };
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["pdfFile-UpdateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["pdfFile-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Pings */
  get_pings_api_pings_get: {
    parameters: {
      query?: {
        "page[size]"?: number;
        "page[number]"?: number;
        sort?: string;
        include?: string;
        "filter[message]"?: string;
        "filter[prev]"?: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["ping-PageOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Ping */
  create_ping_api_pings_post: {
    parameters: {
      query?: {
        include?: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ping-CreateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/vnd.api+json": components["schemas"]["ping-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Ping */
  get_ping_api_pings__id__get: {
    parameters: {
      query?: {
        include?: string;
      };
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["ping-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Ping */
  delete_ping_api_pings__id__delete: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Ping */
  update_ping_api_pings__id__patch: {
    parameters: {
      query?: {
        include?: string;
      };
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ping-UpdateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["ping-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Extraction Report */
  extraction_report_api_project__project_id__extraction_report_json_get: {
    parameters: {
      path: {
        project_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Export Project */
  export_project_api_project__project_id__html_get: {
    parameters: {
      path: {
        project_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Projects */
  get_projects_api_projects_get: {
    parameters: {
      query?: {
        "page[size]"?: number;
        "page[number]"?: number;
        sort?: string;
        include?: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["project-PageOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Project */
  create_project_api_projects_post: {
    parameters: {
      query?: {
        include?: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["project-CreateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/vnd.api+json": components["schemas"]["project-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Project */
  get_project_api_projects__id__get: {
    parameters: {
      query?: {
        include?: string;
      };
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["project-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Project */
  delete_project_api_projects__id__delete: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Project */
  update_project_api_projects__id__patch: {
    parameters: {
      query?: {
        include?: string;
      };
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["project-UpdateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["project-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Sections */
  get_sections_api_sections_get: {
    parameters: {
      query?: {
        "page[size]"?: number;
        "page[number]"?: number;
        sort?: string;
        include?: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["section-PageOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Section */
  create_section_api_sections_post: {
    parameters: {
      query?: {
        include?: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["section-CreateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/vnd.api+json": components["schemas"]["section-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Section */
  get_section_api_sections__id__get: {
    parameters: {
      query?: {
        include?: string;
      };
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["section-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Section */
  delete_section_api_sections__id__delete: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Section */
  update_section_api_sections__id__patch: {
    parameters: {
      query?: {
        include?: string;
      };
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["section-UpdateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["section-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Select Words */
  create_select_words_api_selectWordss_post: {
    parameters: {
      query?: {
        include?: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["selectWords-CreateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/vnd.api+json": components["schemas"]["selectWords-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Select Words */
  get_select_words_api_selectWordss__id__get: {
    parameters: {
      query?: {
        include?: string;
      };
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["selectWords-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Select Words */
  delete_select_words_api_selectWordss__id__delete: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Select Words */
  update_select_words_api_selectWordss__id__patch: {
    parameters: {
      query?: {
        include?: string;
      };
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["selectWords-UpdateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["selectWords-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Textbooks */
  get_textbooks_api_textbooks_get: {
    parameters: {
      query?: {
        "page[size]"?: number;
        "page[number]"?: number;
        sort?: string;
        include?: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["textbook-PageOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Textbook */
  create_textbook_api_textbooks_post: {
    parameters: {
      query?: {
        include?: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["textbook-CreateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/vnd.api+json": components["schemas"]["textbook-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Textbook */
  get_textbook_api_textbooks__id__get: {
    parameters: {
      query?: {
        include?: string;
      };
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["textbook-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Textbook */
  delete_textbook_api_textbooks__id__delete: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Textbook */
  update_textbook_api_textbooks__id__patch: {
    parameters: {
      query?: {
        include?: string;
      };
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["textbook-UpdateInput"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/vnd.api+json": components["schemas"]["textbook-ItemOutput"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Login */
  login_api_token_post: {
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_token_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Reset For Tests */
  reset_for_tests_reset_for_tests_yes_im_sure_post: {
    parameters: {
      query?: {
        fixtures?: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
