# https://docs.docker.com/compose/compose-file/

name: gabby-dev

services:
  fanout:
    image: nginx:latest
    ports:
      - "${GABBY_DEV_PORT:-8080}:80"
    volumes:
      - ./fanout/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

  backend:
    image: nginx:latest

  frontend:
    build: frontend
    volumes:
      - ../frontend:/app
      # This caching of 'node_modules' interferes with Cypress' cache
      # @todo Improve as explained here:
      # https://docs.cypress.io/guides/continuous-integration/introduction#Caching
      - frontend-node-modules:/app/node_modules
    working_dir: /app
    environment:
      VITE_GABBY_VERSION: dev
    command: [ "bash", "-c", "npm install && npx vite --host 0.0.0.0 --port 80 --strictPort" ]

volumes:
  frontend-node-modules:
