# https://docs.docker.com/compose/compose-file/

name: gabby-dev

services:
  frontend:
    build: frontend
    ports:
      - "${GABBY_DEV_PORT:-8080}:8080"
    volumes:
      - ../frontend:/app
      # 'node_modules' not cached, to let Cypress' cache do its thing. Could be improved as described here:
      # https://docs.cypress.io/guides/continuous-integration/introduction#Caching
      - /app/node_modules
    working_dir: /app
    environment:
      PORT: 80
      VITE_GABBY_VERSION: dev
    command: [ "bash", "-c", "npm install && exec npm run dev" ]
