# https://docs.docker.com/compose/compose-file/

name: gabby-dev

services:
  fanout:
    image: nginx:latest
    ports:
      - "${GABBY_DEV_PORT:-8080}:80"
    volumes:
      - ./fanout/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: ../backend
      dockerfile: ../dev-env/backend/Dockerfile
    volumes:
      - ../backend:/app
    working_dir: /app
    command: ["python", "manage.py", "runserver", "0.0.0.0:80"]
    depends_on:
      db:
        condition: service_healthy
  # @todo Find a maintained alternative to either of these two images
  adminer:
    image: adminer:4
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: db
      ADMINER_DEFAULT_DB_NAME: gabby
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: gabby
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gabby
    healthcheck:
      test: [
        "CMD",
        "pg_isready",
        "--timeout=0",
        "--dbname=gabby",
        "--username=gabby",
      ]
      start_period: 0s
      interval: 0.5s
      timeout: 1s
      retries: 10

  frontend:
    build: frontend
    volumes:
      - ../frontend:/app
      # This caching of 'node_modules' interferes with Cypress' cache
      # @todo Improve as explained here:
      # https://docs.cypress.io/guides/continuous-integration/introduction#Caching
      - frontend-node-modules:/app/node_modules
    working_dir: /app
    environment:
      VITE_GABBY_VERSION: dev
    command: ["bash", "-c", "npm install && npx vite --host 0.0.0.0 --port 80 --strictPort"]

volumes:
  db-data:
  frontend-node-modules:
